[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "math_package_xgqfrms"
version = "0.0.2"
authors = [
  { name="xgqfrms", email="xgqfrms@xgqfrms.xyz" },
]
description = "A math package of python 3. ğŸ"
# summary = "Addition, subtraction, multiplication and division"
# Additional properties are not allowed ('summary' was unexpected)Even Better TOML âŒ
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: MIT License",
]
keywords = [
  "math",
  "package",
  "python",
  "xgqfrms",
  "linux",
]
license = "MIT"
# license_files = "LICENSE"
# Additional properties are not allowed ('license_files' was unexpected)Even Better TOML âŒ



[project.urls]
"PyPi ğŸ" = "https://pypi.org/project/math-package-xgqfrms/"
"Website ğŸŒ" = "https://math_package_project.xgqfrms.xyz/"
"GitHub ğŸ™" = "https://github.com/xgqfrms/math_package_project"
"Issues â“" = "https://github.com/xgqfrms/math_package_project/issues"
"Wiki ğŸ—‚ï¸" = "https://github.com/xgqfrms/math_package_project/issues"
